# Generated by Django 2.1.2 on 2018-11-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181101_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default='no_image_available.png', upload_to=''),
        ),
    ]
